<%@ Page Title="" Language="C#" MasterPageFile="~/Index.Master" AutoEventWireup="true" CodeBehind="expense.aspx.cs" Inherits="Inventory.expense" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <style type="text/css">
        .maincont{
            width:100%;
            margin:0px auto;
            padding:0px;
            overflow:hidden;
            height:auto;
            position:relative;
        }
        .heading{
            width:80%;margin-right:20%;height:50px;
            overflow:hidden;
            color:red;
            text-align:center;
        }
        .cont{
            width:80%;margin-right:20%;height:auto;
            overflow:hidden;
            margin-top:100px;
        }
         .left{
            width:50%;
            float:left;
            height:auto;
            overflow:hidden;
        }
        .right{
            width:49%;
            float:right;
            height:auto;
            overflow:hidden;
        }
        .auto-style2 {
            width: 100%;
        }
        .auto-style3 {
            width: 170px;
        }
        .auto-style4 {
            width: 170px;
            font-weight: bold;
        }
        .auto-style5 {
            width: 181px;
            font-weight: bold;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="maincont">
        <div class="heading">
        <h1>Expense</h1>
        </div>
        <div class="cont">
            <div class="left">

                <table class="auto-style2">
                    <tr>
                        <td class="auto-style4">EXPENSE AMOUNT</td>
                        <td>
                            <asp:TextBox ID="txtexpenseamount" placeholder="Enter Amount" runat="server" Height="29px" Width="239px"></asp:TextBox>
&nbsp;</td>
                    </tr>
                    <tr>
                        <td class="auto-style4">EXPENSE PURPOSE</td>
                        <td>
                            <asp:TextBox ID="txtpurpose" placeholder="Enter Purpose" TextMode="MultiLine" runat="server" Height="69px" Width="239px"></asp:TextBox>
&nbsp; </td>
                    </tr>
                    <tr>
                        <td class="auto-style3">&nbsp;</td>
                        <td>
                            <asp:TextBox ID="txtdate" runat="server" Width="218px"></asp:TextBox>
&nbsp;</td>
                    </tr>
                    <tr>
                        <td class="auto-style3">&nbsp;</td>
                        <td>
                            <asp:Calendar ID="Calendar1" runat="server" Width="227px" OnSelectionChanged="Calendar1_SelectionChanged"></asp:Calendar>
&nbsp;</td>
                    </tr>
                    <tr>
                        <td class="auto-style3">&nbsp;</td>
                        <td>
                            <asp:Button ID="Button9" runat="server" Text="SUBMIT" Width="157px" style="font-weight: 700" OnClick="Button9_Click" />
&nbsp;</td>
                    </tr>
                    <tr>
                        <td class="auto-style3">&nbsp;</td>
                        <td>
                            <asp:Label ID="lblmsg" ForeColor="Blue" runat="server" Text=""></asp:Label>
                        </td>
                    </tr>
                </table>

            </div>
             <div class="right">

                 <table class="auto-style2">
                     <tr>
                         <td class="auto-style5">TODAY TOTAL EXPENSE</td>
                         <td>
                             <asp:Label ID="lbldaytotal" runat="server" Text=""></asp:Label>
                         </td>
                     </tr>
                     <tr>
                         <td class="auto-style5">MONTHLY TOTAL EXPENSE</td>
                         <td>
                             <asp:Label ID="lblmonthtotal" runat="server" Text=""></asp:Label>
                         </td>
                     </tr>
                     <tr>
                         <td class="auto-style5">YEAR TOTAL EXPENSE</td>
                         <td>
                             <asp:Label ID="lblyeartotal" runat="server" Text=""></asp:Label>
                         </td>
                     </tr>
                 </table>
                 <br />

                 <asp:GridView ID="GridView1" runat="server" BackColor="White" BorderColor="#3366CC" BorderStyle="None" BorderWidth="1px" CellPadding="4" Width="446px" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="expenseID" DataSourceID="SqlDataSource1">
                     <Columns>
                         <asp:BoundField DataField="expenseID" HeaderText="expenseID" InsertVisible="False" ReadOnly="True" SortExpression="expenseID" />
                         <asp:BoundField DataField="expenseAmount" HeaderText="expenseAmount" SortExpression="expenseAmount" />
                         <asp:BoundField DataField="expensePurpose" HeaderText="expensePurpose" SortExpression="expensePurpose" />
                         <asp:BoundField DataField="expenseDay" HeaderText="expenseDay" SortExpression="expenseDay" />
                         <asp:BoundField DataField="expenseMonth" HeaderText="expenseMonth" SortExpression="expenseMonth" />
                         <asp:BoundField DataField="expenseYear" HeaderText="expenseYear" SortExpression="expenseYear" />
                     </Columns>
                     <FooterStyle BackColor="#99CCCC" ForeColor="#003399" />
                     <HeaderStyle BackColor="#003399" Font-Bold="True" ForeColor="#CCCCFF" />
                     <PagerStyle BackColor="#99CCCC" ForeColor="#003399" HorizontalAlign="Left" />
                     <RowStyle BackColor="White" ForeColor="#003399" />
                     <SelectedRowStyle BackColor="#009999" Font-Bold="True" ForeColor="#CCFF99" />
                     <SortedAscendingCellStyle BackColor="#EDF6F6" />
                     <SortedAscendingHeaderStyle BackColor="#0D4AC4" />
                     <SortedDescendingCellStyle BackColor="#D6DFDF" />
                     <SortedDescendingHeaderStyle BackColor="#002876" />
                 </asp:GridView>

                 <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:conn %>" SelectCommand="SELECT * FROM [Expense] ORDER BY [expenseID] DESC" DeleteCommand="delete Expense where expenseID=@expenseID" UpdateCommand="update Expense set expenseAmount=@expenseAmount,expensePurpose=@expensePurpose,expenseDay=@expenseDay,expenseMonth=@expenseMonth,expenseYear=@expenseYear where expenseID=@expenseID"></asp:SqlDataSource>

            </div>
        </div>
    </div>
</asp:Content>
